"""Initial migration

Revision ID: 8d5157421e44
Revises: 
Create Date: 2026-01-26 10:09:16.300619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d5157421e44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['actor_id'], ['id'])

    with op.batch_alter_table('dossier_sav', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'numero_serie', ['numero_serie_id'], ['id'])
        batch_op.create_foreign_key(None, 'numero_serie', ['numero_serie_remplacement_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'intervention', ['intervention_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['cree_par_id'], ['id'])

    with op.batch_alter_table('historique_etat_numero_serie', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'numero_serie', ['numero_serie_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['utilisateur_id'], ['id'])

    with op.batch_alter_table('import_historique_numero_serie', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['utilisateur_id'], ['id'])
        batch_op.create_foreign_key(None, 'produits', ['produit_id'], ['id'])

    with op.batch_alter_table('intervention', schema=None) as batch_op:
        batch_op.alter_column('completeness_score',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sla_escalation_level',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_foreign_key(None, 'user', ['sla_acknowledged_by'], ['id'])
        batch_op.drop_column('sla_hours_override')

    with op.batch_alter_table('intervention_history', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_foreign_key(None, 'intervention', ['intervention_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('kpi_alerte', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'kpi_score', ['kpi_score_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['technicien_id'], ['id'])

    with op.batch_alter_table('kpi_historique', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['technicien_id'], ['id'])

    with op.batch_alter_table('kpi_objectif', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['technicien_id'], ['id'])

    with op.batch_alter_table('kpi_score', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'equipe', ['equipe_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['technicien_id'], ['id'])

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('business_days_count',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['technicien_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['manager_id'], ['id'])
        batch_op.drop_column('commentaire')

    with op.batch_alter_table('mouvement_numero_serie', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'emplacement_stock', ['ancien_emplacement_id'], ['id'])
        batch_op.create_foreign_key(None, 'emplacement_stock', ['nouvel_emplacement_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['utilisateur_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['nouveau_technicien_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['ancien_technicien_id'], ['id'])
        batch_op.create_foreign_key(None, 'numero_serie', ['numero_serie_id'], ['id'])

    with op.batch_alter_table('mouvement_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_state', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('date_approbation', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_execution', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_validation', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approuve_par_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motif_rejet', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('anomalies', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('applique_au_stock', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mouvement_stock_workflow_state'), ['workflow_state'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['approuve_par_id'], ['id'])

    with op.batch_alter_table('numero_serie', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dossier_sav', ['dossier_sav_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['modifie_par_id'], ['id'])
        batch_op.create_foreign_key(None, 'produits', ['produit_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['technicien_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'emplacement_stock', ['emplacement_id'], ['id'])
        batch_op.create_foreign_key(None, 'zone', ['zone_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['cree_par_id'], ['id'])

    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['chef_zone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('numero_serie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mouvement_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_mouvement_stock_workflow_state'))
        batch_op.drop_column('applique_au_stock')
        batch_op.drop_column('anomalies')
        batch_op.drop_column('motif_rejet')
        batch_op.drop_column('approuve_par_id')
        batch_op.drop_column('date_validation')
        batch_op.drop_column('date_execution')
        batch_op.drop_column('date_approbation')
        batch_op.drop_column('workflow_state')

    with op.batch_alter_table('mouvement_numero_serie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('business_days_count',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)

    with op.batch_alter_table('kpi_score', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('kpi_objectif', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('kpi_historique', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('kpi_alerte', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('intervention_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('action',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)

    with op.batch_alter_table('intervention', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_hours_override', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sla_escalation_level',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('completeness_score',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('import_historique_numero_serie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('historique_etat_numero_serie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('dossier_sav', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
